- dockerfile
> improvement: fix setup deployment with CI/CD

- config/load.go
- features/transaction/dtos/request.go
- features/transaction/dtos/response.go
- features/transaction/entities.go
- features/transaction/handler/controller.go
- features/transaction/interfaces.go
- features/transaction/repository/model.go
- features/transaction/usecase/service.go
- go.mod
- go.sum
- helpers/generator.go
- helpers/interface.go
- helpers/midtrans-request.go
- routes/transaction.go
- server.go
- utils/database.go
- utils/midtrans.go
features create transaction ahdn handle midtrans notifications
> feat: create transaction and handle midtrans notifications

- features/transaction/dtos/response.go
- features/transaction/entities.go
- features/transaction/handler/controller.go
- features/transaction/interfaces.go
- features/transaction/repository/model.go
- features/transaction/usecase/service.go
- routes/transaction.go
- server.go
Add limit using idRole , and add pagination for fetch all transactions
> Transactions

- features/volunteer/dtos/request.go
- features/volunteer/dtos/response.go
- features/volunteer/handler/controller.go
- features/volunteer/interfaces.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
update:
1. fix searching volunteer vacancies
2. implement pagination by helper
> Improvement in volunteers

- features/user/dtos/request.go
- features/user/dtos/response.go
- features/user/handler/controller.go
- features/user/interfaces.go
- features/user/usecase/service.go
- helpers/interface.go
- helpers/jwt.go
- routes/user.go
updates: 
1. separate user data update and profile picture update
2. add feature my profile
3. add feature refresh jwt
4. implement pagination by helper
> Update feature auth

- features/fundraise/handler/controller.go
- features/fundraise/interfaces.go
- features/fundraise/repository/model.go
- features/fundraise/usecase/service.go
- helpers/interface.go
- helpers/mocks/CloudStorageInterface.go
- helpers/mocks/JWTInterface.go
- helpers/mocks/MidtransInterface.go
- helpers/upload-file.go
remove overwritten file system, change to insert a new one and delete the old one.
> fix and improvement: delete file from the bucket

- features/auth/dtos/request.go
- features/auth/usecase/service.go
- features/user/interfaces.go
- features/user/repository/model.go
- features/user/usecase/service.go
- helpers/interface.go
- helpers/jwt.go
- helpers/mocks/JWTInterface.go
updates:
1. fix feature refresh JWT
2. change link default profile picture
3. refactor logic change profile picture
4. update mock in helpers
> Fix and improvement in auth and user

- features/volunteer/dtos/request.go
- features/volunteer/dtos/response.go
- features/volunteer/entities.go
- features/volunteer/handler/controller.go
- features/volunteer/interfaces.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
Updates:
1. improvement logic upload file
2. fixed bug in feature apply vacancy
3. add rejected reason for volunteer vacancy submission
4. add validation and add rejected reason for registrar vacancy
> Updates in volunteers

- .github/workflows/docker-image.yml
- features/fundraise/handler/controller.go
- features/fundraise/interfaces.go
- features/fundraise/usecase/service.go
- features/news/handler/controller.go
- features/news/interfaces.go
- features/news/usecase/service.go
- features/volunteer/handler/controller.go
- features/volunteer/interfaces.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
- Add openai key for chatbot
- Add delete feature to fundraise and news
> Improvement

- features/auth/dtos/request.go
- features/auth/handler/handler.go
- features/auth/interface.go
- features/auth/usecase/service.go
- features/auth/usecase/service_test.go
- features/user/dtos/request.go
- features/user/handler/controller.go
- features/user/interfaces.go
- features/user/repository/model.go
- features/user/usecase/service.go
- middlewares/jwt-auth.go
- routes/user.go
Updates:
1. set endpoint for mobile
2. improve update data and create endpoint update data from user and admin
3. add feature change password
4. improve validation at login and register user
> Update in auth and user

- features/transaction/handler/controller.go
Fix error parsing role id because it changed
> Transactions : Fix error parsing jwt id role

- features/auth/dtos/request.go
- features/auth/entity.go
- features/user/dtos/request.go
- features/user/entities.go
- features/user/handler/controller.go
- features/user/interfaces.go
- features/user/usecase/service.go
- helpers/request-validation.go
- routes/user.go
Updates:
1. add feature personalization
2. fix validation at update user
> Updates in user

- features/volunteer/handler/controller.go
- features/volunteer/interfaces.go
- features/volunteer/mocks/Repository.go
- features/volunteer/mocks/Usecase.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
- features/volunteer/usecase/service_test.go
Update : check already vacancy before create
> Update in volunteer

- features/user/dtos/response.go
- features/user/handler/controller.go
- features/user/interfaces.go
- features/user/usecase/service.go
Update:
1. add NIK to my profile response
> Update in Auth

- features/chatbot/dtos/response.go
- features/chatbot/entities.go
- features/chatbot/usecase/service.go
add timestamp for chat history
> fix: add timestamp for chat

- features/history/handler/controller.go
fix combining all history to one array
> fix: combine all history to one slices

- features/user/handler/controller.go
- features/user/interfaces.go
- features/user/usecase/service.go
Updates:
1. Fixed error message when delete user
2. Fixed error message when update user
> Updates in Auth

- features/volunteer/entities.go
- features/volunteer/interfaces.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
Updates:
1. add created at, updated at, and deleted at in table volunteer relations 
2. fix minor bug
> Updates in Volunteer Vacancy

- features/fundraise/entities.go
- features/fundraise/interfaces.go
- features/fundraise/repository/model.go
- features/fundraise/usecase/service.go
- features/volunteer/entities.go
- features/volunteer/interfaces.go
- features/volunteer/repository/model.go
- features/volunteer/usecase/service.go
- features/volunteer/usecase/service_test.go
- server.go
Update: add notification when update status vacancy and registrant
> Volunteers

- config/load.go
- features/transaction/usecase/service.go
- helpers/midtrans-request.go
> refractor : update paid at time at paid transaction
